### PR TITLE
backwards compatibility with python2.7

### LINKED ISSUE #86: backwards compatibility with python 2.7
container-transform is currently not backwards compatible with python 2.7:

`Traceback (most recent call last):
  File "/usr/local/bin/container-transform", line 9, in <module>
    load_entry_point('container-transform==1.1.5', 'console_scripts', 'container-transform')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/container_transform/__init__.py", line 3, in <module>
    from .converter import Converter
  File "/Library/Python/2.7/site-packages/container_transform/converter.py", line 3, in <module>
    from .compose import ComposeTransformer
  File "/Library/Python/2.7/site-packages/container_transform/compose.py", line 6, in <module>
    from .transformer import BaseTransformer
  File "/Library/Python/2.7/site-packages/container_transform/transformer.py", line 38
    class BaseTransformer(object, metaclass=ABCMeta):
                                           ^
SyntaxError: invalid syntax`

### PR DESCRIPTION
**Pull request by malachany**
fixes [86](https://github.com/micahhausler/container-transform/issues/86)

tested with python2.7 and python3.6

### CODE REVIEW

**Comment by malachany** [comment]
failing due to kubernetes test:

`container_transform/kubernetes.py      170    170     92      0     0%`

**Comment by malachany** [comment]
@micahhausler, Is there anyway to get this merged without the Kubernetes tests?

**Comment by micahhausler** [comment]
Hey thanks, but I actually removed up 2.7 in #37 as it is no longer being developed

**Comment by malachany** [comment]
Ohh, I see. Ok, thanks.

**Pull request closed without merging**
